### ISSUE TITLE
Issue with a private repository

### ISSUE THREAD

**Issue by antonk52** [lfre/lightkeeper#3] opened 2019-08-16 21:28 UTC
Hi, thanks a lot for the awesome project!

I have ran into an issue. I wanted to try out lightkeeper in a project that is stored in a private repo on github and deployed using zeit's now. I've took a look at the examples in your readme and essentially copied the default settings with the zeit now baseUrl, type and ci properties. You can see an example of `lightkeeper.json` file below. The issue I faced is that on a pull request there were no visible checks from lightkeeper. However, the app did deploy a branch copy with `now`. Another thing I noticed is that if i go to `github.com/<user>/<project>/pull/123/checks` I could see that the check was queued up as you can see from the screenshot below.

<img width="352" alt="Screen Shot 2019-08-17 at 12 03 47 AM" src="https://user-images.githubusercontent.com/5817809/63199026-3aba9300-c085-11e9-948c-989f6e3f609e.png">

After rereading the docs I tried to add the exact same config in a similar project, yet it is stored in a public repo ([PR](https://github.com/antonk52/thebowl.moscow/pull/4)). At the end I am still not sure if having it to run on a private repo requires an undocumented extra step? If so I am happy to add it to the docs but I have not figured it out yet.

Update: turns out even on the public repo it seems like it ran lighthouse against `zeit.co` instead of the deployment of my branch.

<details>
<summary><code>.github/lightkeeper.json</code>  file</summary>
<pre>
{
  "baseUrl": "{target_url}",
  "ci": "now",
  "type": "deployment",
  "settings": {
    "categories": {
      "performance": 58,
      "accessibility": 57,
      "best-practices": 64
    },
    "budgets": [
      {
        "resourceSizes": [
          {
            "resourceType": "script",
            "budget": 300
          },
          {
            "resourceType": "image",
            "budget": 100
          },
          {
            "resourceType": "third-party",
            "budget": 200
          },
          {
            "resourceType": "total",
            "budget": 1000
          }
        ],
        "resourceCounts": [
          {
            "resourceType": "third-party",
            "budget": 50
          },
          {
            "resourceType": "total",
            "budget": 50
          }
        ]
      }
    ]
  },
  "routes": [
    "/"
  ]
}
</pre>
</details>

**Comment by lfre** [comment] 2019-08-17 20:15
Thanks for the issue @antonk52. There shouldn't any additional steps for private repos. I see the requests in the logs for `nataxo/gerda` (correct me if I'm wrong). I'll take a look, since I'm currently addressing https://github.com/lfre/lightkeeper/issues/2.

Regarding the other issue (URL). I'm not seeing `thebowlmoscow-git-feature-lightkeeper.antonk52.now.sh` anywhere in the response from Now. I'll confirm if this is a recent change on their side (which would be unfortunate).

**Comment by antonk52** [comment] 2019-08-17 20:33
Thank you for the quick response!

Yep, both `nataxo/gerda` and `antonk52/thebowl.moscow` are the repos I've tried lightkeeper on.

**Comment by lfre** [comment] 2019-08-18 21:27
@antonk52 I can confirm Zeit updated their app to change the `target_url` to the deployment url at zeit.co. I see there is an `environment_url` available at the deployment status. This requires another Github API query, so I'll be adding that. 

In the meantime, you can use the other available macros to form the default alias Zeit creates. `https://myrepo-git-{branch}.foo.now.sh`. This currently requires the branch names to have dashes and not slashes. This makes me realize string macros should get `slugified`.

Thanks again for your feedback and for using the app!

**Comment by antonk52** [comment] 2019-08-18 21:34
Thanks for the reply. If I got that right this example with a `branch` in the url won't work for my case where the branch name is `feature/lightkeeper`. I guess I am going to let that PR to hang for now. But I do look forward for this to work with zeit now out of the box. It is an amazing tool which will definitely help to keep an eye on app's performance.

**Comment by lfre** [comment] 2019-08-19 02:23
Here's the fix for enabling Zeit deployments to work out of the box https://github.com/lfre/lightkeeper/pull/4. It also adds a "slugified" version of branch and repo names as macros.

~~The private issue remains unfortunately. The Github search API is not working as expected https://developer.github.com/v3/search/#search-commits. Needs more investigation.~~

Figured out an alternative that _should_ fix the private issue.

Will run some tests, and merge hopefully tomorrow 👍

**Comment by antonk52** [comment] 2019-08-19 14:31
Hello again, I've found an interesting case. I've tried the suggestion with the `{branch}` in the name and it seems like the rest of the string got cut off.

set `baseUrl` - `https://thebowlmoscow-git-{branch}.antonk52.now.sh/`
what lightkeeper got - `https://thebowlmoscow-git-feature/`

you can see it in action [here](https://github.com/antonk52/thebowl.moscow/pull/4)

**Comment by lfre** [comment] 2019-08-19 15:00
yes @antonk52 that's due to the slash in the name, which will be fixed by the slugify addition. However, I do see a use case of wanting the `baseUrl` to include a slug like `https://thebowlmoscow-git-feature-branch.antonk52.now.sh/slug`, so every other route is added to that, currently (even with the upcoming changes) `/slug` would still be removed. I'll address that as well.

**Closed as completed** 2019-08-20 02:49 UTC
Labels: bug

**Comment by lfre** [comment] 2019-08-20 02:51
This is fixed @antonk52. Hope that helps! In case it wasn't clear from above, you'll have to switch to `{environment_url}` for your `baseUrl`. Docs have been updated as well 👍
